### PR TITLE
Build for CUDA 9.2/10.0/10.1

### PR DESCRIPTION
**Pull request by leofang**
Build for all CUDA versions currently existing on Conda-Forge by managing conda_build_config.yml ourselves. Also add myself as a maintainer. 

MNT: Re-rendered with conda-build 3.20.3, conda-smithy 3.9.0, and conda-forge-pinning 2021.02.26.11.24.58

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
I thought we already confirmed these were built last night. Or is there some other reason we need this?

**Comment by leofang** [comment]
Yes, so this is mainly to prepare for future nccl version bumps and migrations, see @kkraus14's comment: https://github.com/conda-forge/cupy-feedstock/pull/102#issuecomment-786439224.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Leo! 😄

**Pull request merged**
